// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::aptos_constantinople_demo_map_init {
    use aptos_constantinople_demo::encounter_trigger;
    use aptos_constantinople_demo::map;
    use aptos_constantinople_demo::obstruction;
    use aptos_constantinople_demo::map_service;

    public entry fun initialize(store_account: &signer) {
        obstruction::initialize(store_account);
        encounter_trigger::initialize(store_account);
        map::initialize(store_account);
        map_service::initialize(store_account);
    }

}
