// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::aptos_constantinople_demo_init {
    use aptos_constantinople_demo::genesis_account;
    use aptos_constantinople_demo::map;
    use aptos_constantinople_demo::monster;

    public entry fun initialize(account: &signer) {
        genesis_account::initialize(account);
        monster::initialize(account);
        map::initialize(account);
    }

}
