// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::aptos_constantinople_demo_init {
    use aptos_constantinople_demo::encounter;
    use aptos_constantinople_demo::encounter_trigger;
    use aptos_constantinople_demo::encounterable;
    use aptos_constantinople_demo::genesis_account;
    use aptos_constantinople_demo::map;
    use aptos_constantinople_demo::monster;
    use aptos_constantinople_demo::movable;
    use aptos_constantinople_demo::obstruction;
    use aptos_constantinople_demo::owned_monsters;
    use aptos_constantinople_demo::player;
    use aptos_constantinople_demo::player_position;
    use aptos_constantinople_demo::random_seed;

    public entry fun initialize(account: &signer) {
        genesis_account::initialize(account);
        player::initialize(account);
        movable::initialize(account);
        encounterable::initialize(account);
        monster::initialize(account);
        obstruction::initialize(account);
        encounter_trigger::initialize(account);
        player_position::initialize(account);
        encounter::initialize(account);
        owned_monsters::initialize(account);
        random_seed::initialize(account);
        map::initialize(account);
    }

}
