// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::encounter_created {

    use aptos_constantinople_demo::encounter::{Self, EncounterCreated};

    public fun player_id(encounter_created: &EncounterCreated): address {
        encounter::encounter_created_player_id(encounter_created)
    }

    public fun is_existent(encounter_created: &EncounterCreated): bool {
        encounter::encounter_created_is_existent(encounter_created)
    }

    public fun monster_id(encounter_created: &EncounterCreated): address {
        encounter::encounter_created_monster_id(encounter_created)
    }

    public fun catch_attempts(encounter_created: &EncounterCreated): u64 {
        encounter::encounter_created_catch_attempts(encounter_created)
    }

}
