// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::encounter_updated {

    use aptos_constantinople_demo::encounter::{Self, EncounterUpdated};

    public fun player_id(encounter_updated: &EncounterUpdated): address {
        encounter::encounter_updated_player_id(encounter_updated)
    }

    public fun is_existent(encounter_updated: &EncounterUpdated): bool {
        encounter::encounter_updated_is_existent(encounter_updated)
    }

    public fun monster_id(encounter_updated: &EncounterUpdated): address {
        encounter::encounter_updated_monster_id(encounter_updated)
    }

    public fun catch_attempts(encounter_updated: &EncounterUpdated): u64 {
        encounter::encounter_updated_catch_attempts(encounter_updated)
    }

}
