// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::encounterable_created {

    use aptos_constantinople_demo::encounterable::{Self, EncounterableCreated};

    public fun player_id(encounterable_created: &EncounterableCreated): address {
        encounterable::encounterable_created_player_id(encounterable_created)
    }

    public fun value(encounterable_created: &EncounterableCreated): bool {
        encounterable::encounterable_created_value(encounterable_created)
    }

}
