// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::encounter_trigger_created {

    use aptos_constantinople_demo::encounter_trigger::{Self, EncounterTriggerCreated};
    use aptos_constantinople_demo::position::Position;

    public fun position(encounter_trigger_created: &EncounterTriggerCreated): Position {
        encounter_trigger::encounter_trigger_created_position(encounter_trigger_created)
    }

    public fun value(encounter_trigger_created: &EncounterTriggerCreated): bool {
        encounter_trigger::encounter_trigger_created_value(encounter_trigger_created)
    }

}
