// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::encounterable_updated {

    use aptos_constantinople_demo::encounterable::{Self, EncounterableUpdated};

    public fun player_id(encounterable_updated: &EncounterableUpdated): address {
        encounterable::encounterable_updated_player_id(encounterable_updated)
    }

    public fun value(encounterable_updated: &EncounterableUpdated): bool {
        encounterable::encounterable_updated_value(encounterable_updated)
    }

}
