// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::encounter_deleted {

    use aptos_constantinople_demo::encounter::{Self, EncounterDeleted};

    public fun player_id(encounter_deleted: &EncounterDeleted): address {
        encounter::encounter_deleted_player_id(encounter_deleted)
    }

}
