// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::encounter_trigger_aggregate {
    use aptos_constantinople_demo::encounter_trigger;
    use aptos_constantinople_demo::encounter_trigger_create_logic;
    use aptos_constantinople_demo::position::{Self, Position};

    public(friend) fun create(
        account: &signer,
        position_x: u64,
        position_y: u64,
        value: bool,
    ) {
        let position: Position = position::new(
            position_x,
            position_y,
        );

        let encounter_trigger_created = encounter_trigger_create_logic::verify(
            account,
            position,
            value,
        );
        let encounter_trigger = encounter_trigger_create_logic::mutate(
            account,
            &encounter_trigger_created,
        );
        encounter_trigger::add_encounter_trigger(encounter_trigger);
        encounter_trigger::emit_encounter_trigger_created(encounter_trigger_created);
    }

}
