// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::monster_created {

    use aptos_constantinople_demo::monster::{Self, MonsterCreated};

    public fun monster_id(monster_created: &MonsterCreated): address {
        monster::monster_created_monster_id(monster_created)
    }

    public fun monster_type(monster_created: &MonsterCreated): u64 {
        monster::monster_created_monster_type(monster_created)
    }

}
