// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::monster_deleted {

    use aptos_constantinople_demo::monster::{Self, MonsterDeleted};

    public fun monster_id(monster_deleted: &MonsterDeleted): address {
        monster::monster_deleted_monster_id(monster_deleted)
    }

}
