// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::monster_added_to_player {

    use aptos_constantinople_demo::owned_monsters::{Self, MonsterAddedToPlayer};

    public fun player_id(monster_added_to_player: &MonsterAddedToPlayer): address {
        owned_monsters::monster_added_to_player_player_id(monster_added_to_player)
    }

    public fun monster_id(monster_added_to_player: &MonsterAddedToPlayer): address {
        owned_monsters::monster_added_to_player_monster_id(monster_added_to_player)
    }

}
