// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::movable_created {

    use aptos_constantinople_demo::movable::{Self, MovableCreated};

    public fun player_id(movable_created: &MovableCreated): address {
        movable::movable_created_player_id(movable_created)
    }

    public fun value(movable_created: &MovableCreated): bool {
        movable::movable_created_value(movable_created)
    }

}
