// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::obstruction_created {

    use aptos_constantinople_demo::obstruction::{Self, ObstructionCreated};
    use aptos_constantinople_demo::position::Position;

    public fun position(obstruction_created: &ObstructionCreated): Position {
        obstruction::obstruction_created_position(obstruction_created)
    }

    public fun value(obstruction_created: &ObstructionCreated): bool {
        obstruction::obstruction_created_value(obstruction_created)
    }

}
