// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::obstruction {
    use aptos_constantinople_demo::genesis_account;
    use aptos_constantinople_demo::pass_object;
    use aptos_constantinople_demo::position::Position;
    use aptos_framework::account;
    use aptos_framework::event;
    use aptos_std::table::{Self, Table};
    friend aptos_constantinople_demo::obstruction_create_logic;
    friend aptos_constantinople_demo::obstruction_aggregate;

    const EIdAlreadyExists: u64 = 101;
    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const ENotInitialized: u64 = 110;

    struct Events has key {
        obstruction_created_handle: event::EventHandle<ObstructionCreated>,
    }

    struct Tables has key {
        obstruction_table: Table<Position, Obstruction>,
    }

    public fun initialize(account: &signer) {
        genesis_account::assert_genesis_account(account);

        let res_account = genesis_account::resource_account_signer();
        move_to(&res_account, Events {
            obstruction_created_handle: account::new_event_handle<ObstructionCreated>(&res_account),
        });

        move_to(
            &res_account,
            Tables {
                obstruction_table: table::new(),
            },
        );

    }

    struct Obstruction has store {
        position: Position,
        version: u64,
        value: bool,
    }

    public fun position(obstruction: &Obstruction): Position {
        obstruction.position
    }

    public fun version(obstruction: &Obstruction): u64 {
        obstruction.version
    }

    public(friend) fun set_value(obstruction: &mut Obstruction, value: bool) {
        obstruction.value = value;
    }

    fun new_obstruction(
        position: Position,
        value: bool,
    ): Obstruction {
        Obstruction {
            position,
            version: 0,
            value,
        }
    }

    struct ObstructionCreated has store, drop {
        position: Position,
        value: bool,
    }

    public fun obstruction_created_position(obstruction_created: &ObstructionCreated): Position {
        obstruction_created.position
    }

    public fun obstruction_created_value(obstruction_created: &ObstructionCreated): bool {
        obstruction_created.value
    }

    public(friend) fun new_obstruction_created(
        position: Position,
        value: bool,
    ): ObstructionCreated {
        ObstructionCreated {
            position,
            value,
        }
    }


    public(friend) fun create_obstruction(
        position: Position,
        value: bool,
    ): Obstruction acquires Tables {
        asset_obstruction_not_exists(position);
        let obstruction = new_obstruction(
            position,
            value,
        );
        obstruction
    }

    public(friend) fun asset_obstruction_not_exists(
        position: Position,
    ) acquires Tables {
        assert!(exists<Tables>(genesis_account::resouce_account_address()), ENotInitialized);
        let tables = borrow_global_mut<Tables>(genesis_account::resouce_account_address());
        assert!(!table::contains(&tables.obstruction_table, position), EIdAlreadyExists);
    }

    public(friend) fun update_version_and_add(obstruction: Obstruction) acquires Tables {
        obstruction.version = obstruction.version + 1;
        //assert!(obstruction.version != 0, EInappropriateVersion);
        private_add_obstruction(obstruction);
    }

    public(friend) fun add_obstruction(obstruction: Obstruction) acquires Tables {
        assert!(obstruction.version == 0, EInappropriateVersion);
        private_add_obstruction(obstruction);
    }

    public(friend) fun remove_obstruction(position: Position): Obstruction acquires Tables {
        assert!(exists<Tables>(genesis_account::resouce_account_address()), ENotInitialized);
        let tables = borrow_global_mut<Tables>(genesis_account::resouce_account_address());
        table::remove(&mut tables.obstruction_table, position)
    }

    fun private_add_obstruction(obstruction: Obstruction) acquires Tables {
        assert!(exists<Tables>(genesis_account::resouce_account_address()), ENotInitialized);
        let tables = borrow_global_mut<Tables>(genesis_account::resouce_account_address());
        table::add(&mut tables.obstruction_table, position(&obstruction), obstruction);
    }

    public fun get_all_porperties(position: Position): bool acquires Tables {
        assert!(exists<Tables>(genesis_account::resouce_account_address()), ENotInitialized);
        let tables = borrow_global<Tables>(genesis_account::resouce_account_address());
        let obstruction = table::borrow(&tables.obstruction_table, position);
        obstruction.value
    }

    public(friend) fun drop_obstruction(obstruction: Obstruction) {
        let Obstruction {
            version: _version,
            position: _position,
            value: _value,
        } = obstruction;
    }

    public fun contains_obstruction(position: Position): bool acquires Tables {
        let tables = borrow_global<Tables>(genesis_account::resouce_account_address());
        table::contains(&tables.obstruction_table,  position)
    }

    public(friend) fun emit_obstruction_created(obstruction_created: ObstructionCreated) acquires Events {
        assert!(exists<Events>(genesis_account::resouce_account_address()), ENotInitialized);
        let events = borrow_global_mut<Events>(genesis_account::resouce_account_address());
        event::emit_event(&mut events.obstruction_created_handle, obstruction_created);
    }

}
