// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::owned_monsters_created {

    use aptos_constantinople_demo::owned_monsters::{Self, OwnedMonstersCreated};

    public fun player_id(owned_monsters_created: &OwnedMonstersCreated): address {
        owned_monsters::owned_monsters_created_player_id(owned_monsters_created)
    }

    public fun monsters(owned_monsters_created: &OwnedMonstersCreated): vector<address> {
        owned_monsters::owned_monsters_created_monsters(owned_monsters_created)
    }

}
