// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::player_position_updated {

    use aptos_constantinople_demo::player_position::{Self, PlayerPositionUpdated};
    use aptos_constantinople_demo::position::Position;

    public fun player_id(player_position_updated: &PlayerPositionUpdated): address {
        player_position::player_position_updated_player_id(player_position_updated)
    }

    public fun position(player_position_updated: &PlayerPositionUpdated): Position {
        player_position::player_position_updated_position(player_position_updated)
    }

}
