// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::player {
    use aptos_framework::account;
    use aptos_framework::event;
    use aptos_std::table::{Self, Table};
    friend aptos_constantinople_demo::player_create_logic;
    friend aptos_constantinople_demo::player_aggregate;

    const EIdAlreadyExists: u64 = 101;
    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const ENotInitialized: u64 = 110;

    struct Events has key {
        player_created_handle: event::EventHandle<PlayerCreated>,
    }

    struct Tables has key {
        player_table: Table<address, Player>,
    }

    public fun initialize(store_account: &signer) {
        move_to(store_account, Events {
            player_created_handle: account::new_event_handle<PlayerCreated>(store_account),
        });

        move_to(
            store_account,
            Tables {
                player_table: table::new(),
            },
        );

    }

    struct Player has store {
        player_id: address,
        version: u64,
        value: bool,
    }

    public fun player_id(player: &Player): address {
        player.player_id
    }

    public fun version(player: &Player): u64 {
        player.version
    }

    public(friend) fun set_value(player: &mut Player, value: bool) {
        player.value = value;
    }

    fun new_player(
        player_id: address,
        value: bool,
    ): Player {
        Player {
            player_id,
            version: 0,
            value,
        }
    }

    struct PlayerCreated has store, drop {
        player_id: address,
        value: bool,
    }

    public fun get_player_created_all_properties(player_created: &PlayerCreated): (address, bool) {
        (player_created.player_id, player_created.value)
    }

    public(friend) fun new_player_created(
        player_id: address,
        value: bool,
    ): PlayerCreated {
        PlayerCreated {
            player_id,
            value,
        }
    }


    public(friend) fun create_player(
        store_address: address,
        player_id: address,
        value: bool,
    ): Player acquires Tables {
        asset_player_not_exists(store_address, player_id);
        let player = new_player(
            player_id,
            value,
        );
        player
    }

    public(friend) fun asset_player_not_exists(
        store_address: address, player_id: address,
    ) acquires Tables {
        assert!(exists<Tables>(store_address), ENotInitialized);
        let tables = borrow_global_mut<Tables>(store_address);
        assert!(!table::contains(&tables.player_table, player_id), EIdAlreadyExists);
    }

    public(friend) fun update_version_and_add(store_address: address, player: Player) acquires Tables {
        player.version = player.version + 1;
        //assert!(player.version != 0, EInappropriateVersion);
        private_add_player(store_address, player);
    }

    public(friend) fun add_player(store_address: address, player: Player) acquires Tables {
        assert!(player.version == 0, EInappropriateVersion);
        private_add_player(store_address, player);
    }

    public(friend) fun remove_player(store_address: address, player_id: address): Player acquires Tables {
        assert!(exists<Tables>(store_address), ENotInitialized);
        let tables = borrow_global_mut<Tables>(store_address);
        table::remove(&mut tables.player_table, player_id)
    }

    fun private_add_player(store_address: address, player: Player) acquires Tables {
        assert!(exists<Tables>(store_address), ENotInitialized);
        let tables = borrow_global_mut<Tables>(store_address);
        table::add(&mut tables.player_table, player.player_id, player);
    }

    public fun get_all_porperties(store_address: address, player_id: address): bool acquires Tables {
        assert!(exists<Tables>(store_address), ENotInitialized);
        let tables = borrow_global<Tables>(store_address);
        let player = table::borrow(&tables.player_table, player_id);
        all_porperties(player)
    }

    public fun all_porperties(player: &Player): bool {
        player.value
    }

    public(friend) fun drop_player(player: Player) {
        let Player {
            version: _version,
            player_id: _player_id,
            value: _value,
        } = player;
    }

    public fun contains_player(store_address: address, player_id: address): bool acquires Tables {
        let tables = borrow_global<Tables>(store_address);
        table::contains(&tables.player_table, player_id)
    }

    public(friend) fun emit_player_created(store_address: address, player_created: PlayerCreated) acquires Events {
        assert!(exists<Events>(store_address), ENotInitialized);
        let events = borrow_global_mut<Events>(store_address);
        event::emit_event(&mut events.player_created_handle, player_created);
    }

}
