// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::player_created {

    use aptos_constantinople_demo::player::{Self, PlayerCreated};

    public fun player_id(player_created: &PlayerCreated): address {
        player::player_created_player_id(player_created)
    }

    public fun value(player_created: &PlayerCreated): bool {
        player::player_created_value(player_created)
    }

}
