// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::player_position_created {

    use aptos_constantinople_demo::player_position::{Self, PlayerPositionCreated};
    use aptos_constantinople_demo::position::Position;

    public fun player_id(player_position_created: &PlayerPositionCreated): address {
        player_position::player_position_created_player_id(player_position_created)
    }

    public fun position(player_position_created: &PlayerPositionCreated): Position {
        player_position::player_position_created_position(player_position_created)
    }

}
