// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::player_updated {

    use aptos_constantinople_demo::player::{Self, PlayerUpdated};

    public fun player_id(player_updated: &PlayerUpdated): address {
        player::player_updated_player_id(player_updated)
    }

    public fun value(player_updated: &PlayerUpdated): bool {
        player::player_updated_value(player_updated)
    }

}
