// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::player_aggregate {
    use aptos_constantinople_demo::player;
    use aptos_constantinople_demo::player_create_logic;

    friend aptos_constantinople_demo::rpg_service;

    public(friend) fun create(
        account: &signer,
        store: address,
        player_id: address,
        value: bool,
    ) {
        let player_created = player_create_logic::verify(
            account,
            store,
            player_id,
            value,
        );
        let player = player_create_logic::mutate(
            account,
            store,
            &player_created,
        );
        player::add_player(store, player);
        player::emit_player_created(store, player_created);
    }

}
