// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::random_seed_aggregate {
    use aptos_constantinople_demo::random_seed;
    use aptos_constantinople_demo::random_seed_update_logic;

    friend aptos_constantinople_demo::rpg_service;

    public(friend) fun update(
        account: &signer,
        store: address,
        value: u64,
    ) {
        // let random_seed = random_seed::remove_random_seed(store, );
        // let random_seed_updated = random_seed_update_logic::verify(
        //     account,
        //     store,
        //     value,
        //     &random_seed,
        // );
        // let updated_random_seed = random_seed_update_logic::mutate(
        //     account,
        //     &random_seed_updated,
        //     random_seed,
        // );
        // random_seed::update_version_and_add(store, updated_random_seed);//todo !!!
        // random_seed::emit_random_seed_updated(store, random_seed_updated);
    }

}
