// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::random_seed_updated {

    use aptos_constantinople_demo::random_seed::{Self, RandomSeedUpdated};

    public fun value(random_seed_updated: &RandomSeedUpdated): u64 {
        random_seed::random_seed_updated_value(random_seed_updated)
    }

}
