// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::random_seed_aggregate {
    use aptos_constantinople_demo::random_seed;

    friend aptos_constantinople_demo::rpg_service;

}
