// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::aptos_constantinople_demo_init {
    use aptos_constantinople_demo::encounter;
    use aptos_constantinople_demo::encounterable;
    use aptos_constantinople_demo::monster;
    use aptos_constantinople_demo::movable;
    use aptos_constantinople_demo::owned_monsters;
    use aptos_constantinople_demo::player;
    use aptos_constantinople_demo::player_position;
    use aptos_constantinople_demo::random_seed;
    use aptos_constantinople_demo::rpg_service;

    public entry fun initialize(store_account: &signer) {
        player::initialize(store_account);
        movable::initialize(store_account);
        encounterable::initialize(store_account);
        monster::initialize(store_account);
        player_position::initialize(store_account);
        encounter::initialize(store_account);
        owned_monsters::initialize(store_account);
        random_seed::initialize(store_account);
        rpg_service::initialize(store_account);
    }

}
