// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_constantinople_demo::player_position_aggregate {
    use aptos_constantinople_demo::player_position;
    use aptos_constantinople_demo::player_position_create_logic;
    use aptos_constantinople_demo::player_position_update_logic;
    use aptos_constantinople_demo::position::Position;

    friend aptos_constantinople_demo::rpg_service;

    public(friend) fun create(
        account: &signer,
        store_address: address,
        player_id: address,
        position: Position,
    ) {
        let player_position_created = player_position_create_logic::verify(
            account,
            store_address,
            player_id,
            position,
        );
        let player_position = player_position_create_logic::mutate(
            account,
            store_address,
            &player_position_created,
        );
        player_position::add_player_position(store_address, player_position);
        player_position::emit_player_position_created(store_address, player_position_created);
    }

    public(friend) fun update(
        account: &signer,
        store_address: address,
        player_id: address,
        position: Position,
    ) {
        let player_position = player_position::remove_player_position(store_address, player_id);
        let player_position_updated = player_position_update_logic::verify(
            account,
            store_address,
            position,
            &player_position,
        );
        let updated_player_position = player_position_update_logic::mutate(
            account,
            &player_position_updated,
            player_position,
        );
        player_position::update_version_and_add(store_address, updated_player_position);
        player_position::emit_player_position_updated(store_address, player_position_updated);
    }

}
